// <auto-generated>
class ELIFE_ProvisionedPhoneCallback : ELIFE_BaseRestCallback
{
	override ELIFE_EApiStatusCode ExtractData(string data, int dataSize, out JsonApiStruct resultData)
	{
		resultData = new ELIFE_ProvisionedPhone();
		resultData.ExpandFromRAW(data);
		if (!resultData)
			return ELIFE_EApiStatusCode.ERROR;
		return ELIFE_EApiStatusCode.SUCCESS;
	}
}
