// <auto-generated>
modded class ELIFE_Api
{
	void Ping(Managed instance = null, string functionName = "")
	{
		ELIFE_PingResponseCallback cbx = new ELIFE_PingResponseCallback;
		cbx.SetCallback(instance, functionName);
		GetElifeApi().GET(cbx, "ping");
	}

	void Health(Managed instance = null, string functionName = "")
	{
		ELIFE_HealthReportCallback cbx = new ELIFE_HealthReportCallback;
		cbx.SetCallback(instance, functionName);
		GetElifeApi().GET(cbx, "health");
	}

	void HealthLive(Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName);
		GetElifeApi().GET(cbx, "health/live");
	}

	void HealthReady(Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName);
		GetElifeApi().GET(cbx, "health/ready");
	}
}
