// <auto-generated>
modded class ELIFE_Api
{
	void OpenBank(ELIFE_OpenBankRequest body, Managed instance = null, string functionName = "")
	{
		ELIFE_BankSummaryCallback cbx = new ELIFE_BankSummaryCallback;
		cbx.SetCallback(instance, functionName);
		body.Pack();
		GetElifeApi().POST(cbx, "banks", body.AsString());
	}

	void ListBanks(Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName);
		GetElifeApi().GET(cbx, "banks");
	}

	void OpenBankAccount(ELIFE_OpenBankAccountRequestDto body, string bankId, Managed instance = null, string functionName = "")
	{
		ELIFE_BankAccountSummaryCallback cbx = new ELIFE_BankAccountSummaryCallback;
		cbx.SetCallback(instance, functionName, bankId);
		body.Pack();
		GetElifeApi().POST(cbx, string.Format("banks/%1/accounts", bankId), body.AsString());
	}

	void ListCharacterBankAccounts(string characterId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, characterId);
		GetElifeApi().GET(cbx, string.Format("characters/%1/bank-accounts", characterId));
	}

	void ListCompanyBankAccounts(string companyId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, companyId);
		GetElifeApi().GET(cbx, string.Format("companies/%1/bank-accounts", companyId));
	}

	void GetBankAccount(string bankAccountId, Managed instance = null, string functionName = "")
	{
		ELIFE_BankAccountSummaryCallback cbx = new ELIFE_BankAccountSummaryCallback;
		cbx.SetCallback(instance, functionName, bankAccountId);
		GetElifeApi().GET(cbx, string.Format("bank-accounts/%1", bankAccountId));
	}

	void ListBankAccountTransactions(string bankAccountId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, bankAccountId);
		GetElifeApi().GET(cbx, string.Format("bank-accounts/%1/transactions", bankAccountId));
	}

	void DepositToBankAccount(ELIFE_DepositRequest body, string bankAccountId, Managed instance = null, string functionName = "")
	{
		ELIFE_TransactionResultCallback cbx = new ELIFE_TransactionResultCallback;
		cbx.SetCallback(instance, functionName, bankAccountId);
		body.Pack();
		GetElifeApi().PUT(cbx, string.Format("bank-accounts/%1/deposit", bankAccountId), body.AsString());
	}

	void WithdrawFromBankAccount(ELIFE_WithdrawRequest body, string bankAccountId, Managed instance = null, string functionName = "")
	{
		ELIFE_TransactionResultCallback cbx = new ELIFE_TransactionResultCallback;
		cbx.SetCallback(instance, functionName, bankAccountId);
		body.Pack();
		GetElifeApi().PUT(cbx, string.Format("bank-accounts/%1/withdraw", bankAccountId), body.AsString());
	}

	void TransferBankAccountFunds(ELIFE_TransferRequest body, string bankAccountId, Managed instance = null, string functionName = "")
	{
		ELIFE_TransactionResultCallback cbx = new ELIFE_TransactionResultCallback;
		cbx.SetCallback(instance, functionName, bankAccountId);
		body.Pack();
		GetElifeApi().PUT(cbx, string.Format("bank-accounts/%1/transaction", bankAccountId), body.AsString());
	}
}
