// <auto-generated>
modded class ELIFE_Api
{
	void PlayerConnected(ELIFE_PlayerConnectedRequest body, Managed instance = null, string functionName = "")
	{
		ELIFE_PlayerConnectedResponseCallback cbx = new ELIFE_PlayerConnectedResponseCallback;
		cbx.SetCallback(instance, functionName);
		body.Pack();
		GetElifeApi().POST(cbx, "player-connected", body.AsString());
	}

	void CharacterSelected(ELIFE_CharacterSelectedRequest body, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName);
		body.Pack();
		GetElifeApi().POST(cbx, "character-selected", body.AsString());
	}

	void PlayerDisconnected(ELIFE_PlayerDisconnectedRequest body, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName);
		body.Pack();
		GetElifeApi().POST(cbx, "player-disconnected", body.AsString());
	}
}
