// <auto-generated>
modded class ELIFE_Api
{
	void CreateCharacter(ELIFE_CreateCharacterRequest body, Managed instance = null, string functionName = "")
	{
		ELIFE_CharacterSummaryCallback cbx = new ELIFE_CharacterSummaryCallback;
		cbx.SetCallback(instance, functionName);
		body.Pack();
		GetElifeApi().POST(cbx, "characters", body.AsString());
	}

	void ListCharacters(string bohemiaId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName);
		GetElifeApi().GET(cbx, string.Format("characters?bohemiaId=%1", bohemiaId));
	}
}
