// <auto-generated>
modded class ELIFE_Api
{
	void ProvisionPhone(ELIFE_ProvisionPhoneRequest body, Managed instance = null, string functionName = "")
	{
		ELIFE_ProvisionedPhoneCallback cbx = new ELIFE_ProvisionedPhoneCallback;
		cbx.SetCallback(instance, functionName);
		body.Pack();
		GetElifeApi().POST(cbx, "phones", body.AsString());
	}

	void ListCharacterPhones(string characterId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, characterId);
		GetElifeApi().GET(cbx, string.Format("characters/%1/phones", characterId));
	}

	void GetPhone(string phoneId, Managed instance = null, string functionName = "")
	{
		ELIFE_PhoneSummaryCallback cbx = new ELIFE_PhoneSummaryCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		GetElifeApi().GET(cbx, string.Format("phones/%1", phoneId));
	}

	void SetPhonePower(ELIFE_SetPhonePowerRequest body, string phoneId, Managed instance = null, string functionName = "")
	{
		ELIFE_PhonePowerStateCallback cbx = new ELIFE_PhonePowerStateCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		body.Pack();
		GetElifeApi().POST(cbx, string.Format("phones/%1/power", phoneId), body.AsString());
	}

	void ChangePhonePin(ELIFE_ChangePhonePinRequest body, string phoneId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		body.Pack();
		GetElifeApi().POST(cbx, string.Format("phones/%1/pin", phoneId), body.AsString());
	}

	void ListPhoneApps(string phoneId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		GetElifeApi().GET(cbx, string.Format("phones/%1/apps", phoneId));
	}

	void InstallPhoneApp(ELIFE_PhoneActorRequest body, string phoneId, string appKey, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		body.Pack();
		GetElifeApi().PUT(cbx, string.Format("phones/%1/apps/%2", phoneId, appKey), body.AsString());
	}

	void UninstallPhoneApp(string phoneId, string appKey, string characterId, string pin, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		GetElifeApi().DELETE(cbx, string.Format("phones/%1/apps/%2?characterId=%3&pin=%4", phoneId, appKey, characterId, pin), "");
	}

	void SuspendPhone(ELIFE_SuspendPhoneRequest body, string phoneId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		body.Pack();
		GetElifeApi().POST(cbx, string.Format("phones/%1/suspend", phoneId), body.AsString());
	}

	void RestorePhone(string phoneId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		GetElifeApi().POST(cbx, string.Format("phones/%1/restore", phoneId), "");
	}

	void ListPhoneContacts(string phoneId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		GetElifeApi().GET(cbx, string.Format("phones/%1/apps/contacts/entries", phoneId));
	}

	void SavePhoneContact(ELIFE_SavePhoneContactRequest body, string phoneId, Managed instance = null, string functionName = "")
	{
		ELIFE_SavedContactCallback cbx = new ELIFE_SavedContactCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		body.Pack();
		GetElifeApi().POST(cbx, string.Format("phones/%1/apps/contacts/entries", phoneId), body.AsString());
	}

	void DeletePhoneContact(string phoneId, string contactId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		GetElifeApi().DELETE(cbx, string.Format("phones/%1/apps/contacts/entries/%2", phoneId, contactId), "");
	}

	void PollPhoneMessages(string phoneId, string since, Managed instance = null, string functionName = "")
	{
		ELIFE_MessageUpdatesCallback cbx = new ELIFE_MessageUpdatesCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		GetElifeApi().GET(cbx, string.Format("phones/%1/apps/messages/updates?since=%2", phoneId, since));
	}

	void ListPhoneThreads(string phoneId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		GetElifeApi().GET(cbx, string.Format("phones/%1/apps/messages/threads", phoneId));
	}

	void GetPhoneThread(string phoneId, string threadId, Managed instance = null, string functionName = "")
	{
		ELIFE_MessageThreadDetailCallback cbx = new ELIFE_MessageThreadDetailCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		GetElifeApi().GET(cbx, string.Format("phones/%1/apps/messages/threads/%2", phoneId, threadId));
	}

	void SendPhoneMessage(ELIFE_SendPhoneMessageRequest body, string phoneId, Managed instance = null, string functionName = "")
	{
		ELIFE_SentMessageCallback cbx = new ELIFE_SentMessageCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		body.Pack();
		GetElifeApi().POST(cbx, string.Format("phones/%1/apps/messages/send", phoneId), body.AsString());
	}

	void MarkPhoneThreadRead(string phoneId, string threadId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		GetElifeApi().POST(cbx, string.Format("phones/%1/apps/messages/threads/%2/read", phoneId, threadId), "");
	}

	void BlockPhoneNumber(ELIFE_BlockPhoneNumberRequest body, string phoneId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		body.Pack();
		GetElifeApi().POST(cbx, string.Format("phones/%1/apps/messages/blocks", phoneId), body.AsString());
	}

	void UnblockPhoneNumber(string phoneId, string number, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, phoneId);
		GetElifeApi().DELETE(cbx, string.Format("phones/%1/apps/messages/blocks/%2", phoneId, number), "");
	}
}
