// <auto-generated>
modded class ELIFE_Api
{
	void CreateCompany(ELIFE_CreateCompanyRequest body, Managed instance = null, string functionName = "")
	{
		ELIFE_CompanySummaryCallback cbx = new ELIFE_CompanySummaryCallback;
		cbx.SetCallback(instance, functionName);
		body.Pack();
		GetElifeApi().POST(cbx, "companies", body.AsString());
	}

	void ListCompanies(Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName);
		GetElifeApi().GET(cbx, "companies");
	}

	void GetCompany(string companyId, Managed instance = null, string functionName = "")
	{
		ELIFE_CompanyDetailsCallback cbx = new ELIFE_CompanyDetailsCallback;
		cbx.SetCallback(instance, functionName, companyId);
		GetElifeApi().GET(cbx, string.Format("companies/%1", companyId));
	}

	void AddCompanyMember(ELIFE_AddCompanyMemberRequest body, string companyId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, companyId);
		body.Pack();
		GetElifeApi().POST(cbx, string.Format("companies/%1/members", companyId), body.AsString());
	}

	void SubmitCompanyApplication(ELIFE_SubmitCompanyApplicationRequest body, string companyId, Managed instance = null, string functionName = "")
	{
		ELIFE_CompanyApplicationSummaryCallback cbx = new ELIFE_CompanyApplicationSummaryCallback;
		cbx.SetCallback(instance, functionName, companyId);
		body.Pack();
		GetElifeApi().POST(cbx, string.Format("companies/%1/applications", companyId), body.AsString());
	}

	void ListCompanyApplications(string companyId, string actingCharacterId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, companyId);
		GetElifeApi().GET(cbx, string.Format("companies/%1/applications?actingCharacterId=%2", companyId, actingCharacterId));
	}

	void ConfirmCompanyApplication(ELIFE_ActingCharacterRequest body, string companyId, string applicationId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, companyId);
		body.Pack();
		GetElifeApi().PUT(cbx, string.Format("companies/%1/applications/%2/confirm", companyId, applicationId), body.AsString());
	}

	void AcceptCompanyApplication(ELIFE_ActingCharacterRequest body, string companyId, string applicationId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, companyId);
		body.Pack();
		GetElifeApi().PUT(cbx, string.Format("companies/%1/applications/%2/accept", companyId, applicationId), body.AsString());
	}

	void DenyCompanyApplication(ELIFE_ActingCharacterRequest body, string companyId, string applicationId, Managed instance = null, string functionName = "")
	{
		ELIFE_BaseRestCallback cbx = new ELIFE_BaseRestCallback;
		cbx.SetCallback(instance, functionName, companyId);
		body.Pack();
		GetElifeApi().PUT(cbx, string.Format("companies/%1/applications/%2/deny", companyId, applicationId), body.AsString());
	}
}
