// <auto-generated>
class ELIFE_SentMessage : JsonApiStruct
{
	string threadId;
	string messageId;
	ref array<string> undeliverableRecipients = {};

	void ELIFE_SentMessage()
	{
		RegV("threadId");
		RegV("messageId");
		RegV("undeliverableRecipients");
	}
}
