// <auto-generated>
class ELIFE_BankAccountSummary : JsonApiStruct
{
	string bankAccountId;
	string bankId;
	string number;
	string type;
	string characterId;
	string companyId;
	float balance;

	void ELIFE_BankAccountSummary()
	{
		RegV("bankAccountId");
		RegV("bankId");
		RegV("number");
		RegV("type");
		RegV("characterId");
		RegV("companyId");
		RegV("balance");
	}
}
