// <auto-generated>
class ELIFE_PlayerConnectedResponse : JsonApiStruct
{
	string accountId;
	ELIFE_PlayerSessionStatus status;
	string linkPin;
	ref array<ref ELIFE_CharacterSummary> characters = {};

	void ELIFE_PlayerConnectedResponse()
	{
		RegV("accountId");
		RegV("status");
		RegV("linkPin");
		RegV("characters");
	}
}
