// <auto-generated>
class ELIFE_HealthReport : JsonApiStruct
{
	ELIFE_HealthStatus status;
	string checkedAt;
	ref array<ref ELIFE_DependencyHealth> dependencies = {};

	void ELIFE_HealthReport()
	{
		RegV("status");
		RegV("checkedAt");
		RegV("dependencies");
	}
}
