// <auto-generated>
class ELIFE_PhoneMessage : JsonApiStruct
{
	string messageId;
	string from;
	string body;
	string sentAt;
	bool isOutbound;

	void ELIFE_PhoneMessage()
	{
		RegV("messageId");
		RegV("from");
		RegV("body");
		RegV("sentAt");
		RegV("isOutbound");
	}
}
