// <auto-generated>
class ELIFE_SubmitCompanyApplicationRequest : JsonApiStruct
{
	string characterId;
	string message;

	void ELIFE_SubmitCompanyApplicationRequest()
	{
		RegV("characterId");
		RegV("message");
	}
}
