// <auto-generated>
class ELIFE_MessageThreadDetail : JsonApiStruct
{
	string threadId;
	ref array<string> participants = {};
	int unreadCount;
	string lastMessageAt;
	ref array<ref ELIFE_PhoneMessage> messages = {};

	void ELIFE_MessageThreadDetail()
	{
		RegV("threadId");
		RegV("participants");
		RegV("unreadCount");
		RegV("lastMessageAt");
		RegV("messages");
	}
}
