// <auto-generated>
class ELIFE_ProblemDetails : JsonApiStruct
{
	string type;
	string title;
	int status;
	string detail;
	string instance;

	void ELIFE_ProblemDetails()
	{
		RegV("type");
		RegV("title");
		RegV("status");
		RegV("detail");
		RegV("instance");
	}
}
