// <auto-generated>
class ELIFE_TransferRequest : JsonApiStruct
{
	float amount;
	string characterId;
	string targetBankAccountId;

	void ELIFE_TransferRequest()
	{
		RegV("amount");
		RegV("characterId");
		RegV("targetBankAccountId");
	}
}
