// <auto-generated>
class ELIFE_CompanyDetails : JsonApiStruct
{
	string companyId;
	string name;
	ref array<ref ELIFE_CompanyMember> members = {};

	void ELIFE_CompanyDetails()
	{
		RegV("companyId");
		RegV("name");
		RegV("members");
	}
}
