// <auto-generated>
class ELIFE_MessageThreadSummary : JsonApiStruct
{
	string threadId;
	ref array<string> participants = {};
	int unreadCount;
	string lastMessageAt;

	void ELIFE_MessageThreadSummary()
	{
		RegV("threadId");
		RegV("participants");
		RegV("unreadCount");
		RegV("lastMessageAt");
	}
}
