// <auto-generated>
class ELIFE_PhoneSummary : JsonApiStruct
{
	string phoneId;
	string number;
	string registeredTo;
	ELIFE_PhoneStatus status;
	bool isPoweredOn;
	ref array<string> blockedNumbers = {};
	ref array<string> installedApps = {};

	void ELIFE_PhoneSummary()
	{
		RegV("phoneId");
		RegV("number");
		RegV("registeredTo");
		RegV("status");
		RegV("isPoweredOn");
		RegV("blockedNumbers");
		RegV("installedApps");
	}
}
