// <auto-generated>
class ELIFE_ChangePhonePinRequest : JsonApiStruct
{
	string characterId;
	string newPin;
	string pin;

	void ELIFE_ChangePhonePinRequest()
	{
		RegV("characterId");
		RegV("newPin");
		RegV("pin");
	}
}
