// <auto-generated>
class ELIFE_OpenBankRequest : JsonApiStruct
{
	string name;
	float transactionFeeBase;
	float transactionFeeMultiplier;

	void ELIFE_OpenBankRequest()
	{
		RegV("name");
		RegV("transactionFeeBase");
		RegV("transactionFeeMultiplier");
	}
}
