// <auto-generated>
class ELIFE_CompanySummary : JsonApiStruct
{
	string companyId;
	string name;
	int memberCount;

	void ELIFE_CompanySummary()
	{
		RegV("companyId");
		RegV("name");
		RegV("memberCount");
	}
}
