// <auto-generated>
class ELIFE_SetPhonePowerRequest : JsonApiStruct
{
	string characterId;
	bool isPoweredOn;
	string pin;

	void ELIFE_SetPhonePowerRequest()
	{
		RegV("characterId");
		RegV("isPoweredOn");
		RegV("pin");
	}
}
