// <auto-generated>
class ELIFE_CreateCompanyRequest : JsonApiStruct
{
	string name;
	string founderCharacterId;

	void ELIFE_CreateCompanyRequest()
	{
		RegV("name");
		RegV("founderCharacterId");
	}
}
