// <auto-generated>
class ELIFE_CompanyApplicationSummary : JsonApiStruct
{
	string applicationId;
	string characterId;
	string message;
	ELIFE_CompanyApplicationStatus status;

	void ELIFE_CompanyApplicationSummary()
	{
		RegV("applicationId");
		RegV("characterId");
		RegV("message");
		RegV("status");
	}
}
