// <auto-generated>
class ELIFE_ContactSummary : JsonApiStruct
{
	string contactId;
	string number;
	string displayName;

	void ELIFE_ContactSummary()
	{
		RegV("contactId");
		RegV("number");
		RegV("displayName");
	}
}
