// <auto-generated>
class ELIFE_OpenBankAccountRequestDto : JsonApiStruct
{
	string characterId;
	string companyId;

	void ELIFE_OpenBankAccountRequestDto()
	{
		RegV("characterId");
		RegV("companyId");
	}
}
