// <auto-generated>
class ELIFE_MessageUpdates : JsonApiStruct
{
	string polledAt;
	ref array<ref ELIFE_MessageThreadUpdate> threads = {};

	void ELIFE_MessageUpdates()
	{
		RegV("polledAt");
		RegV("threads");
	}
}
