// <auto-generated>
class ELIFE_BankSummary : JsonApiStruct
{
	string bankId;
	string name;
	float transactionFeeBase;
	float transactionFeeMultiplier;

	void ELIFE_BankSummary()
	{
		RegV("bankId");
		RegV("name");
		RegV("transactionFeeBase");
		RegV("transactionFeeMultiplier");
	}
}
