// <auto-generated>
class ELIFE_TransactionResult : JsonApiStruct
{
	float amount;
	float fee;
	float newBalance;

	void ELIFE_TransactionResult()
	{
		RegV("amount");
		RegV("fee");
		RegV("newBalance");
	}
}
