// <auto-generated>
class ELIFE_CharacterSelectedRequest : JsonApiStruct
{
	string bohemiaId;
	string characterId;

	void ELIFE_CharacterSelectedRequest()
	{
		RegV("bohemiaId");
		RegV("characterId");
	}
}
