// <auto-generated>
class ELIFE_BankAccountTransaction : JsonApiStruct
{
	string kind;
	float amount;
	float fee;
	string actingCharacterId;
	string counterpartyBankAccountId;
	string occurredAt;

	void ELIFE_BankAccountTransaction()
	{
		RegV("kind");
		RegV("amount");
		RegV("fee");
		RegV("actingCharacterId");
		RegV("counterpartyBankAccountId");
		RegV("occurredAt");
	}
}
