// <auto-generated>
class ELIFE_DependencyHealth : JsonApiStruct
{
	string name;
	ELIFE_HealthStatus status;
	int durationMs;
	string detail;

	void ELIFE_DependencyHealth()
	{
		RegV("name");
		RegV("status");
		RegV("durationMs");
		RegV("detail");
	}
}
