StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{599ECC80BC741B13}" {
   Id "ELIFE-Item_CarKey_Description"
   Target_en_us "Key for your car"
   Target_de_de "Toller Schlüssel für dein tolles Auto"
   Modified 1503579818
   Author "Nico"
   LastChanged "Nico"
  }
  CustomStringTableItem "{599ECC8085CF8774}" {
   Id "ELIFE-Item_CarKey_Name"
   Target_en_us "Car Key"
   Target_de_de "Autoschlüssel"
   Modified 1503579802
   Author "Nico"
   LastChanged "Nico"
  }
 }
}